name: Test Vars
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "approved"
  approved-condition:
    if: github.event.review.state == 'approved' and github.event.label.sender == ${{ vars.TEST_GH_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "approved-condition"
  approved-another-condition:
    if: github.event.review.state == 'approved' and ${{ github.event.label.sender == vars.TEST_GH_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "approved-another-condition"
  test-display:
    if: github.event.review.state == 'approved' and ${{ github.event.label.sender == vars.TEST_GH_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "test display ${{ github.event.label.sender}} actor ${{ github.actor }} "
