name: Move card in project when design or a11y approved
on:
    pull_request_target:
        types:
            - labeled
            - unlabeled

jobs: 
    design_approved:
        if: contains(github.event.*.labels.*.name, 'passed a11y review') || contains(github.event.*.labels.*.name, 'passed design review') && (!contains(github.event.*.labels.*.name, 'ready for a11y review') || !contains(github.event.*.labels.*.name, 'ready for design review'))
        runs-on: ubuntu-latest
        steps:
            -   name: Get Project Data
                env:
                    GITHUB_TOKEN: ${{ secrets.YOUR_TOKEN }}
                    ORGANIZATION: ${{ github.repository_owner }}
                    PR_ID: ${{ github.event.pull_request.node_id }}
                    PROJECT_NUMBER: 1
                    PROJECT_COL_LEAD_REVIEW: "Need Lead Dev Review"
                run: |
                    gh api graphql -f query='
                    query($org: String!, $number: Int!) {
                        organization(login: $org){
                        projectV2(number: $number) {
                            id
                            fields(first:20) {
                            nodes {
                                ... on ProjectV2Field {
                                id
                                name
                                }
                                ... on ProjectV2SingleSelectField {
                                id
                                name
                                options {
                                    id
                                    name
                                }
                                }
                            }
                            }
                            items(first:20) {
                            nodes {
                                id
                                content {
                                ... on PullRequest {
                                    id
                                }
                                }
                            }
                            }
                        }
                        }
                    }' -f org=$ORGANIZATION -F number=$PROJECT_NUMBER > project_data.json
        
                    echo `cat project_data.json`
        
                    echo 'PROJECT_ID='$(jq '.data.organization.projectV2.id' project_data.json) >> $GITHUB_ENV
                    echo 'STATUS_FIELD_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .id' project_data.json) >> $GITHUB_ENV
                    echo 'TARGET_COL_ID='$(jq '.data.organization.projectV2.fields.nodes[] | select(.name== "Status") | .options[] | select(.name=="${{ env.PROJECT_COL_LEAD_REVIEW }}") |.id' project_data.json) >> $GITHUB_ENV
                    echo 'ITEM_ID='$(jq '.data.organization.projectV2.items.nodes[] | select(.content.id=="${{ env.PR_ID }}") |.id' project_data.json) >> $GITHUB_ENV

            -   name: Change project card to the design and/or accessibility column
                env:
                    GITHUB_TOKEN: ${{ secrets.YOUR_TOKEN }}
                run: |
                    gh api graphql -f query='
                        mutation (
                        $project: ID!
                        $item: ID!
                        $status_field: ID!
                        $status_value: String!
                        ) {
                        set_status: updateProjectV2ItemFieldValue(input: {
                            projectId: $project
                            itemId: $item
                            fieldId: $status_field
                            value: {
                            singleSelectOptionId: $status_value
                            }
                        }) {
                            projectV2Item {
                            id
                            }
                        }
                        }' -f project=$PROJECT_ID -f item=$ITEM_ID -f status_field=$STATUS_FIELD_ID -f status_value=${{ env.TARGET_COL_ID }} --silent