name: Dev reviewed move PR in the right column
on:
  pull_request_review:
    types: 
      - submitted

jobs:
  not-approved:
    if: ${{ github.event.pull_request.draft == false && github.event.review.state == 'changes-requested' && github.actor != vars.LEAD_DEV_GH_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Data
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_TOKEN }}
        run: |
          echo 'not approved'
