name: Update PR
on:
  pull_request:
    types:
      - ready_for_review
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Desc
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_TOKEN }}
          ORGANIZATION: 'ods-sandbox'
          PROJECT_NUMBER: 1
          PR_ID: ${{ github.event.pull_request.node_id }}
          PR_NUMB: ${{ github.event.pull_request.number }}
        run: | 
          gh api graphql -f query='
            query($id: ID!) {
              node(id: $id) {
                ... on PullRequest {
                  body
                }
              }
            }' -f id=$PR_ID > project_data.json
          
          echo `cat project_data.json`

          echo 'PR_DESC='$(jq '.data.node.body' project_data.json | sed "s/{your_pr_number}/${{ env.PR_NUMB }}/g") >> $GITHUB_ENV
          
      - name: Set PR Desc
        env:
          PR_ID: ${{ github.event.pull_request.node_id }}
        run: | 
          gh api graphql -f query='
            mutation (
              $item: ID!
            ) {
              set_status: updatePullRequest(input: {
                pullRequestId: $item
                body: ${{ env.PR_DESC }}
              }) {
                pullRequest {
                  id
                }
              }
            }' -f item=$PR_ID --silent
        